#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 21 15:49:02 2017

@author: hy
"""

./Samples_CoolRunning/test0.tfrecords
(u'prefix/shuffle_batch/random_shuffle_queue', (<tf.Tensor 'prefix/shuffle_batch/random_shuffle_queue:0' shape=() dtype=resource>,))
(u'prefix/shuffle_batch/n', (<tf.Tensor 'prefix/shuffle_batch/n:0' shape=() dtype=int32>,))
(u'prefix/shuffle_batch', (<tf.Tensor 'prefix/shuffle_batch:0' shape=<unknown> dtype=float32>, <tf.Tensor 'prefix/shuffle_batch:1' shape=<unknown> dtype=int64>))
(u'prefix/input_2/shape', (<tf.Tensor 'prefix/input_2/shape:0' shape=(4,) dtype=int32>,))
(u'prefix/input_2', (<tf.Tensor 'prefix/input_2:0' shape=(?, 28, 28, 1) dtype=float32>,))
(u'prefix/layer1-conv1/weight', (<tf.Tensor 'prefix/layer1-conv1/weight:0' shape=(5, 5, 1, 32) dtype=float32>,))
(u'prefix/layer1-conv1/weight/read', (<tf.Tensor 'prefix/layer1-conv1/weight/read:0' shape=(5, 5, 1, 32) dtype=float32>,))
(u'prefix/layer1-conv1/bias', (<tf.Tensor 'prefix/layer1-conv1/bias:0' shape=(32,) dtype=float32>,))
(u'prefix/layer1-conv1/bias/read', (<tf.Tensor 'prefix/layer1-conv1/bias/read:0' shape=(32,) dtype=float32>,))
(u'prefix/layer1-conv1/Conv2D', (<tf.Tensor 'prefix/layer1-conv1/Conv2D:0' shape=(?, 28, 28, 32) dtype=float32>,))
(u'prefix/layer1-conv1/BiasAdd', (<tf.Tensor 'prefix/layer1-conv1/BiasAdd:0' shape=(?, 28, 28, 32) dtype=float32>,))
(u'prefix/layer1-conv1/Relu', (<tf.Tensor 'prefix/layer1-conv1/Relu:0' shape=(?, 28, 28, 32) dtype=float32>,))
(u'prefix/layer2-pool1/MaxPool', (<tf.Tensor 'prefix/layer2-pool1/MaxPool:0' shape=(?, 14, 14, 32) dtype=float32>,))
(u'prefix/layer3-conv2/weight', (<tf.Tensor 'prefix/layer3-conv2/weight:0' shape=(5, 5, 32, 64) dtype=float32>,))
(u'prefix/layer3-conv2/weight/read', (<tf.Tensor 'prefix/layer3-conv2/weight/read:0' shape=(5, 5, 32, 64) dtype=float32>,))
(u'prefix/layer3-conv2/bias', (<tf.Tensor 'prefix/layer3-conv2/bias:0' shape=(64,) dtype=float32>,))
(u'prefix/layer3-conv2/bias/read', (<tf.Tensor 'prefix/layer3-conv2/bias/read:0' shape=(64,) dtype=float32>,))
(u'prefix/layer3-conv2/Conv2D', (<tf.Tensor 'prefix/layer3-conv2/Conv2D:0' shape=(?, 14, 14, 64) dtype=float32>,))
(u'prefix/layer3-conv2/BiasAdd', (<tf.Tensor 'prefix/layer3-conv2/BiasAdd:0' shape=(?, 14, 14, 64) dtype=float32>,))
(u'prefix/layer3-conv2/Relu', (<tf.Tensor 'prefix/layer3-conv2/Relu:0' shape=(?, 14, 14, 64) dtype=float32>,))
(u'prefix/layer4-pool2/MaxPool', (<tf.Tensor 'prefix/layer4-pool2/MaxPool:0' shape=(?, 7, 7, 64) dtype=float32>,))
(u'prefix/layer4-pool2/Reshape/shape', (<tf.Tensor 'prefix/layer4-pool2/Reshape/shape:0' shape=(2,) dtype=int32>,))
(u'prefix/layer4-pool2/Reshape', (<tf.Tensor 'prefix/layer4-pool2/Reshape:0' shape=(64, 3136) dtype=float32>,))
(u'prefix/layer5-fc1/weight', (<tf.Tensor 'prefix/layer5-fc1/weight:0' shape=(3136, 512) dtype=float32>,))
(u'prefix/layer5-fc1/weight/read', (<tf.Tensor 'prefix/layer5-fc1/weight/read:0' shape=(3136, 512) dtype=float32>,))
(u'prefix/layer5-fc1/bias', (<tf.Tensor 'prefix/layer5-fc1/bias:0' shape=(512,) dtype=float32>,))
(u'prefix/layer5-fc1/bias/read', (<tf.Tensor 'prefix/layer5-fc1/bias/read:0' shape=(512,) dtype=float32>,))
(u'prefix/layer5-fc1/MatMul', (<tf.Tensor 'prefix/layer5-fc1/MatMul:0' shape=(64, 512) dtype=float32>,))
(u'prefix/layer5-fc1/add', (<tf.Tensor 'prefix/layer5-fc1/add:0' shape=(64, 512) dtype=float32>,))
(u'prefix/layer5-fc1/Relu', (<tf.Tensor 'prefix/layer5-fc1/Relu:0' shape=(64, 512) dtype=float32>,))
(u'prefix/layer5-fc1/dropout/keep_prob', (<tf.Tensor 'prefix/layer5-fc1/dropout/keep_prob:0' shape=() dtype=float32>,))
(u'prefix/layer5-fc1/dropout/Shape', (<tf.Tensor 'prefix/layer5-fc1/dropout/Shape:0' shape=(2,) dtype=int32>,))
(u'prefix/layer5-fc1/dropout/random_uniform/min', (<tf.Tensor 'prefix/layer5-fc1/dropout/random_uniform/min:0' shape=() dtype=float32>,))
(u'prefix/layer5-fc1/dropout/random_uniform/max', (<tf.Tensor 'prefix/layer5-fc1/dropout/random_uniform/max:0' shape=() dtype=float32>,))
(u'prefix/layer5-fc1/dropout/random_uniform/RandomUniform', (<tf.Tensor 'prefix/layer5-fc1/dropout/random_uniform/RandomUniform:0' shape=(64, 512) dtype=float32>,))
(u'prefix/layer5-fc1/dropout/random_uniform/sub', (<tf.Tensor 'prefix/layer5-fc1/dropout/random_uniform/sub:0' shape=() dtype=float32>,))
(u'prefix/layer5-fc1/dropout/random_uniform/mul', (<tf.Tensor 'prefix/layer5-fc1/dropout/random_uniform/mul:0' shape=(64, 512) dtype=float32>,))
(u'prefix/layer5-fc1/dropout/random_uniform', (<tf.Tensor 'prefix/layer5-fc1/dropout/random_uniform:0' shape=(64, 512) dtype=float32>,))
(u'prefix/layer5-fc1/dropout/add', (<tf.Tensor 'prefix/layer5-fc1/dropout/add:0' shape=(64, 512) dtype=float32>,))
(u'prefix/layer5-fc1/dropout/Floor', (<tf.Tensor 'prefix/layer5-fc1/dropout/Floor:0' shape=(64, 512) dtype=float32>,))
(u'prefix/layer5-fc1/dropout/div', (<tf.Tensor 'prefix/layer5-fc1/dropout/div:0' shape=(64, 512) dtype=float32>,))
(u'prefix/layer5-fc1/dropout/mul', (<tf.Tensor 'prefix/layer5-fc1/dropout/mul:0' shape=(64, 512) dtype=float32>,))
(u'prefix/layer6-fc2/weight', (<tf.Tensor 'prefix/layer6-fc2/weight:0' shape=(512, 10) dtype=float32>,))
(u'prefix/layer6-fc2/weight/read', (<tf.Tensor 'prefix/layer6-fc2/weight/read:0' shape=(512, 10) dtype=float32>,))
(u'prefix/layer6-fc2/bias', (<tf.Tensor 'prefix/layer6-fc2/bias:0' shape=(10,) dtype=float32>,))
(u'prefix/layer6-fc2/bias/read', (<tf.Tensor 'prefix/layer6-fc2/bias/read:0' shape=(10,) dtype=float32>,))
(u'prefix/layer6-fc2/MatMul', (<tf.Tensor 'prefix/layer6-fc2/MatMul:0' shape=(64, 10) dtype=float32>,))
(u'prefix/layer6-fc2/add', (<tf.Tensor 'prefix/layer6-fc2/add:0' shape=(64, 10) dtype=float32>,))
(u'prefix/softmax/predictions', (<tf.Tensor 'prefix/softmax/predictions:0' shape=(64, 10) dtype=float32>,))